### ISSUE TITLE
M1Macの場合、x86_64でビルドされてしまわないか不安...

### ISSUE THREAD

**Issue by tmori** [toppers/hakoniwa-core-cpp-client#55]
以下のように明示した方が良いかもしれない。

```
if(APPLE AND CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "arm64")
    set(CMAKE_OSX_ARCHITECTURES "arm64")
endif()
if(APPLE)
    message(STATUS "CMAKE_OSX_ARCHITECTURES: ${CMAKE_OSX_ARCHITECTURES}")
endif()
```

**Comment by mitsut** [comment]
私の環境では上記の修正をせずにarm64バイナリが作成されています。

@tmori 問題が起こる可能性としては以下が考えられます
- Rosetta2経由(x86_64ターミナルでビルドコマンドを実行する)でビルドをしている
- 依存ライブラリがx86_64しかインストールされていない
- 古いバージョンのCMakeを使用している

上記の提案はMacの場合はArm64固定とするということだと思います。ビルドでエラーになるか、ランタイムでエラーになるかの違いだと思いますがビルドで弾く方針にしますか？
