### ISSUE TITLE
測定結果を評価し、期待通りになっているかチェックする

### ISSUE THREAD

**Issue by tmori** [toppers/hakoniwa-core-cpp-client#67]
# 測定条件

- 固定パラメータ：
  - ステップ数：1,000ステップ
  - ステップ時間：10msec

- 可変パラメータ：
  -  多重度：1, 2, 4, 8, 10
  - MaxDelay: ステップ時間×1, 2, 4, 8, 10
  
- サンプル数：10

  # 評価内容

- 最大許容遅延時間が小さい
  - 箱庭アセット時間の分散は小さいが、並行動作が難しいので、シミュレーション全体の時間は長くなる
- 最大許容遅延時間が大きい
  - 箱庭アセット時間の分散は大きいが、並行動作できるのでシミュレーション全体の時間は短くなる

**Comment by tmori** [comment]
# 箱庭アセット数×総処理時間


- アセット数が増えるに従い、総処理時間は増える。
- 一方で、最大許容遅延時間が増えるにしたいが、総処理時間は提言されていく。

![assetxelapse](https://github.com/user-attachments/assets/891b6425-9ba6-4061-be50-0221a9c4e8fb)

**Comment by tmori** [comment]
# アセット数 x 遅延時間の標準偏差

- 最大遅延時間が増えるに従い、標準偏差は増えるが、だいたい30msec程度で収まっている

![asset-stddev](https://github.com/user-attachments/assets/b675a1a2-7efa-4906-9486-6e492ac5b020)

**Comment by tmori** [comment]
# アセット数10の時の総処理時間x遅延時間の標準偏差

- 総処理時間と標準偏差は反比例の関係（期待通り）
  - 精度高く(最大許容遅延時間を小さくする)すると、総処理時間は増える
  - 精度低く（最大許容遅延時間を大きくする）すると、総処理時間は減る（多重度が上がるので）
- 

![elapse-stddev-m10](https://github.com/user-attachments/assets/0a7090f2-4088-4f85-82de-bf6d9b1f0d0c)

**Comment by tmori** [comment]
縦軸：箱庭時間-箱庭アセット時間
横軸：箱庭時間

# 箱庭のシミュレーション精度変化に対して、想定内の挙動を示しているかどうかを確認する（アセット数=1）

- 最大許容遅延時間：10msec

<img width="984" alt="スクリーンショット 2024-09-21 13 42 17" src="https://github.com/user-attachments/assets/e9eb985d-530b-4c15-9865-511c3bdee8ea">


- 最大許容遅延時間：100msec

<img width="986" alt="スクリーンショット 2024-09-21 13 42 59" src="https://github.com/user-attachments/assets/a695fe3e-5e4b-454c-b97a-10b2ffe7410e">

# 箱庭のシミュレーション精度変化に対して、想定内の挙動を示しているかどうかを確認する（アセット数=2）

- 最大許容遅延時間：10msec

<img width="987" alt="スクリーンショット 2024-09-21 13 46 02" src="https://github.com/user-attachments/assets/0603d8f2-37e6-4851-b351-85f78a213e10">

- 最大許容遅延時間：100msec

<img width="990" alt="スクリーンショット 2024-09-21 13 46 30" src="https://github.com/user-attachments/assets/aa490dd3-ab46-4dbf-abbe-f307983f5c10">



# 箱庭アセット数を増やすことでシミュレーション精度が妥当な範囲になっているか確認する（アセット数=10）


- 最大許容遅延時間：10msec

<img width="985" alt="スクリーンショット 2024-09-21 13 48 31" src="https://github.com/user-attachments/assets/eff51d6e-efec-46ad-91d6-bdb1b83a5b60">


- 最大許容遅延時間：100msec

<img width="994" alt="スクリーンショット 2024-09-21 13 49 06" src="https://github.com/user-attachments/assets/1fe48995-2d3c-498a-a412-d47ddbda1149">

**Comment by kenjihiranabe** [comment]
読み始めました。質問。

ぼくの数学記述では、

- 時刻更新のウォール時間間隔 = Δt 
- シミュレーション時刻のカウントアップ幅 = ΔT

としています。森さんの、

```
固定パラメータ：

ステップ数：1,000ステップ
ステップ時間：10msec
```

のステップ時間は、どちらでしょう？また、もう一つの値はどうなるでしょう？

**Comment by tmori** [comment]
> のステップ時間は、どちらでしょう？また、もう一つの値はどうなるでしょう？

ステップ時間は、こちらに対応します。

* シミュレーション時刻のカウントアップ幅 = ΔT


`時刻更新のウォール時間間隔 = Δt` についてですが、ここはちょっと説明が難しいですね。。

まず、箱庭シミュレーションを現実の時間進行と歩調を合わせたい場合は、箱庭アセット側で明示的にΔT(シミュレーション時刻のカウントアップ幅 )と同じ時間だけ sleep させるようにしています。多分、これが、平鍋さんの定義のウォール時間間隔Δtという解釈でおります。

ただし、この場合、以下の２つの要因により、ウォール時間間隔Δtは、毎回同じ値にはならないと考えております。

- sleep 時間は、汎用OSのスケジューラによるジッタはどうしても入ってしまう
- 箱庭アセットのがシミュレーションとして実行しないとい処理があるので、その時間も含まれてきます

なので、Δt は以下のようになると思います。

Δt = <sleep時間>  + <箱庭アセット処理時間> + <OSジッタ>

<OSジッタ>は、PCの性能に依存しますし、処理負荷が高くなると、幅を利かせてくるような気がしています。

次に、今回の測定についてですが、現実の時間進行と歩調を合わせておりませんので、<sleep時間>は、０にしています。

<箱庭アセット処理時間> については、10000回ビジーループする時間になりますが、ここは測定しておりませんので、どれくらいかはわからない感じです。。

**Comment by kenjihiranabe** [comment]
了解しました。ぼくの方でも、Δt 自身は証明には必要なくて、数列の添字の代わりくらいに思ってもらって（一回づつずれても）大丈夫です。

感覚的には、ウォール時刻 t やサンプリング時間感覚 Δtは「意識していない」もしくは「ループをできるだけ早く回している」ということですね。

また、やろうとすれば、 sleep を入れて明示的に示すことはできるが、どうせ揺れると。ただし、シミュレーション時刻の方は、増加量を一定にしている。

ですかね。

**Comment by tmori** [comment]
> また、やろうとすれば、 sleep を入れて明示的に示すことはできるが、どうせ揺れると。ただし、シミュレーション時刻の方は、増加量 ΔT を一定にしている。
> 
> ですかね。

ですね。

> あと、結果としての毎回の t （ウォール時刻）をログとして出すことは可能ですね？

はい、今回の測定では、`real-time` として、念の為ログ採取しております。

こんな感じです。
[asset-0-measure.csv](https://github.com/user-attachments/files/17142070/asset-0-measure.csv)

**Comment by kenjihiranabe** [comment]
実時間では、結構、コアも揺れますね。もちろん同じPC上で、他のソフトも動いているしね。

<img width="843" alt="image" src="https://github.com/user-attachments/assets/37656439-d931-43cc-8dc4-6aaaa19bcc6c">
